import { assertEquals } from "jsr:@std/assert";
import {  } from "./solution.ts";

Deno.test("simple test", () => {
    const input = 
    `..........
    ..........
    ..........
    ....a.....
    ..........
    .....a....
    ..........
    ..........
    ..........
    ..........`
    
    const output = partOne(input);
    assertEquals(output, 2);
});